name: Test

on:
  pull_request_target:
    types:
      - opened

jobs:
  db-check:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3

      - name: Supabase setup
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start db
        run: supabase db start
