name: Test

on:
  pull_request_target:
    types:
      - opened

jobs:
  db-check:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3

      - name: Supabase setup
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start db
        run: supabase db start

      - name: Migrate db
        run: supabase migration up

      - name: Curl todos
        run: |
          curl 'http://localhost:54321/rest/v1/todos' \
            -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
            -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'
