name: Deploy Function

on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - uses: supabase/supabase@1.187.10
        with:
          version: latest
      - run: npx supabase login --no-browser --token $TOKEN
      - run: supabase functions deploy --project-ref $PROJECT_REF --no-verify-jwt --debug --experimental
      - run: supabase link --project-ref $PROJECT_REF -p $DB_PASSWORD
